# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

branches:
  only:
  - master
dist: bionic
jobs:
  allow_failures:
    os: osx
  fast_finish: true
  include:
  - before_script:
    - make go-build
    env:
    - GO111MODULE=on
    - VERBOSE=1
    go: 1.11.x
    language: go
    os: linux
    script:
    - make go-test
  - before_script:
    - make go-build
    env:
    - GO111MODULE=on
    - VERBOSE=1
    go: 1.11.x
    language: go
    os: osx
    script:
    - make go-test
  - before_script:
    - make go-build
    env:
    - GO111MODULE=on
    - VERBOSE=1
    go: 1.12.x
    language: go
    os: linux
    script:
    - make go-test
  - before_script:
    - make go-build
    env:
    - GO111MODULE=on
    - VERBOSE=1
    go: 1.12.x
    language: go
    os: osx
    script:
    - make go-test
  - before_script:
    - make go-build
    env:
    - GO111MODULE=on
    - VERBOSE=1
    go: 1.13.x
    language: go
    os: linux
    script:
    - make go-test
  - before_script:
    - make go-build
    env:
    - GO111MODULE=on
    - VERBOSE=1
    go: 1.13.x
    language: go
    os: osx
    script:
    - make go-test
  - before_script:
    - make py-install
    env:
    - VERBOSE=1
    language: python
    os: linux
    osx_image: null
    python: "2.7"
    script:
    - make py-test
  - before_script:
    - make py-install
    env:
    - VERBOSE=1
    language: generic
    os: osx
    osx_image: xcode_9.3
    python: null
    script:
    - make py-test
  - before_script:
    - make py-install
    env:
    - VERBOSE=1
    language: python
    os: linux
    osx_image: null
    python: "3.6"
    script:
    - make py-test
  - before_script:
    - make py-install
    env:
    - VERBOSE=1
    language: generic
    os: osx
    osx_image: xcode_9.4
    python: null
    script:
    - make py-test
  - before_script:
    - make py-install
    env:
    - VERBOSE=1
    language: python
    os: linux
    osx_image: null
    python: "3.7"
    script:
    - make py-test
  - before_script:
    - make py-install
    env:
    - VERBOSE=1
    language: generic
    os: osx
    osx_image: xcode_10.2
    python: null
    script:
    - make py-test
language: generic

